language: php

php:
  - 5.5
  - 5.6

# whitelist
branches:
  only:
    - dev

before_script:
   - composer self-update
   - composer install
   - "mysql -utravis -e 'create database if not exists `laraveltesting`;'"
   - php artisan serve &
   - sleep 5

script:
  - vendor/bin/phpunit
  - vendor/bin/behat